### ISSUE TITLE
Adding custom fields in OmniAuth::Form

### ISSUE THREAD

**Issue by hudecof** [robdimarco/omniauth_crowd#24]
It would be nide to have an option to add custom fields /text, hidden/ to the login form.
The gitlab added CSRF protection for omniauth providers, see my MR https://github.com/robdimarco/omniauth_crowd/pull/23.

As I'm no ruby expert, is there any other way to push custom fields into the form or the code needed to be changed?

**Comment by robdimarco** [comment]
Thanks for the pull request, I just merged it.

I think the code would need to be changed to allow for custom fields, happy to look at pull requests.
